name: Selenium Test with Microsoft Edge

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Ajusta la versión de Python según tu necesidad

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download Microsoft Edge WebDriver
        run: |
          curl -sS -o msedgedriver.zip https://msedgedriver.azureedge.net/latest/edgedriver_linux64.zip
          sudo unzip msedgedriver.zip -d /usr/local/bin
          sudo chmod +x /usr/local/bin/msedgedriver

      - name: Run Selenium script
        run: |
          python path/to/your/selenium/script.py  # Ajusta la ruta al script de Selenium
