name: Auto Fichar en Woffu

on:
  push:
    branches:
      - main  # Cambiar por la rama principal de tu repositorio
  pull_request:
    branches:
      - main  # Cambiar por la rama principal de tu repositorio
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install requests
          pip install msedge-selenium-tools

      - name: Download and setup Edge WebDriver
        run: |
          wget https://msedgedriver.azureedge.net/125.0.2535.92/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/msedgedriver
          sudo chmod +x /usr/local/bin/msedgedriver

      - name: Run Selenium script
        env:
          WOFFU_EMAIL: ${{ secrets.WOFFU_EMAIL }}
          WOFFU_PASSWORD: ${{ secrets.WOFFU_PASSWORD }}
        run: python auto_fichar.py
