name: Selenium Test with Microsoft Edge

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Reemplaza '3.x' con la versión específica de Python que necesites

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium msedge-selenium-tools

      - name: Download Microsoft Edge WebDriver
        run: |
          Invoke-WebRequest -Uri "https://msedgedriver.azureedge.net/latest/edgedriver_win64.zip" -OutFile msedgedriver.zip
          Expand-Archive -Path msedgedriver.zip -DestinationPath $env:RUNNER_TEMP

      - name: Set WebDriver Path
        run: |
          $edgedriverPath = Join-Path $env:RUNNER_TEMP "msedgedriver.exe"
          echo "::set-env name=PATH_TO_EDGE_DRIVER::$edgedriverPath"

      - name: Run Selenium script
        env:
          PATH_TO_EDGE_DRIVER: ${{ env.PATH_TO_EDGE_DRIVER }}
        run: |
          python auto_fichar.py  # Reemplaza con el nombre de tu script Selenium
