name: Run Selenium Test Daily

on:
  schedule:
    - cron: '0 8 * * *'  # Ejecutar todos los días a las 8:00 AM UTC (ajustar según tu zona horaria)

jobs:
  test:
    runs-on: windows-latest  # Ejecutar en Windows Latest (Edge)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Selenium and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run Selenium script
        run: python woffu_fichaje.py

      - name: Upload test result
        run: echo 'Test results uploaded successfully'
