name: Selenium Test

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga push a la rama main
  schedule:
    - cron: '0 8 * * *'  # Ejecutar todos los días a las 8:00 AM UTC (ajustar según tu zona horaria)

jobs:
  test:
    runs-on: ubuntu-latest  # Ejecutar en Ubuntu Latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install requests  # Añadir la instalación de requests

      - name: Run Selenium script
        run: python woffu_fichaje.py  # Asegúrate de que este sea el nombre correcto de tu script

      - name: Upload test result
        run: echo 'Test results uploaded successfully'
