name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download msedgedriver.exe
        run: |
          curl -L -o msedgedriver.exe "https://url-del-archivo-msedgedriver.exe"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Selenium and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install msedge-selenium-tools

      - name: Run Selenium script
        run: python woffu_fichaje.py
