name: Selenium Automation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Download and install Microsoft Edge Driver
        run: |
          wget https://msedgedriver.azureedge.net/102.0.1245.41/edgedriver_linux64.zip -O msedgedriver.zip
          sudo apt-get install unzip
          unzip msedgedriver.zip -d /usr/local/bin/
          sudo mv /usr/local/bin/msedgedriver /usr/local/bin/msedgedriver
          sudo chmod +x /usr/local/bin/msedgedriver

      - name: Run Selenium script
        env:
          WOFFU_EMAIL: ${{ secrets.WOFFU_EMAIL }}
          WOFFU_PASSWORD: ${{ secrets.WOFFU_PASSWORD }}
        run: python auto_fichar.py
