name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Selenium and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install msedge-selenium-tools

      - name: Run Selenium script
        run: |
          # Copia msedgedriver.exe desde la ruta Windows a la carpeta actual
          cp /mnt/c/Users/W1VFOUS/OneDrive\ -\ Volkswagen\ AG/Carles_Seat/edgedriver_win64/msedgedriver.exe ./msedgedriver.exe

          # Ejecutar el script Python usando msedgedriver.exe
          python woffu_fichaje.py
