name: Open Google Page with Microsoft Edge

on: [push, pull_request]

jobs:
  open-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium msedge-selenium-tools

      - name: Download Microsoft Edge Driver
        run: |
          curl -LO "https://msedgedriver.azureedge.net/116.0.1938.62/edgedriver_linux64.zip"
          sudo apt-get install -y unzip
          unzip edgedriver_linux64.zip -d /usr/local/bin/

      - name: Run Selenium script
        env:
          MSEDGEDRIVER_PATH: /usr/local/bin/msedgedriver
        run: |
          python open_page.py
