name: Selenium Test with Microsoft Edge

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Reemplaza '3.x' con la versión específica de Python que necesites

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium msedge-selenium-tools

      - name: Download Microsoft Edge Driver
        run: |
          curl -LO "https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/2fe75945-e16c-407b-9a2d-267cc31f3d85/edgedriver_linux64.zip"
          sudo apt-get install -y unzip
          unzip edgedriver_linux64.zip -d /usr/local/bin/
          sudo mv /usr/local/bin/msedgedriver /usr/local/bin/edgedriver

      - name: Run Selenium script
        env:
          MSEDGEDRIVER_PATH: /usr/local/bin/edgedriver
        run: |
          python auto_fichar.py
